%% Code for flowchart below
graph LR
    SSOT[Nodes]

    A[Modify Nodes]
    B[Modify Edges]

    A --modify--> SSOT
    B --update--> SSOT
    SSOT --update--> edges

    graphs[graphs.json]
    backend[Backend]

    SSOT --store--> graphs
    graphs --> backend

  graphs --load--> SSOT
