%% Code for flowchart below
graph LR
    store[store Nodes]

    A[Modify Nodes]
    B[Modify Edges]
    
    A --modify--> store
    B --update--> store
    store --signals--> edges

    graphs[graphs.json]
    backend[Backend]

    store --store--> graphs
    graphs --> backend
    graphs --load--> store